version: '2'

services:
  mysqlmaster:
    container_name: ip_mysql
    image: registry.idmp.tech/library/mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - "./db/master/data:/var/lib/mysql"
      - "./db/master/conf:/etc/mysql/conf.d"
    mem_limit: 512m
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
